### ISSUE TITLE
App is crashing while scanning

### ISSUE THREAD

**Issue by ZakariaJawas** [hannesa2/CVScanPassport#139]
When i start the camera the app is crashing with the following stack
`  java.lang.RuntimeException: Unable to destroy activity {com.debug/info.hannes.cvscanner.DocumentScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
                                                                                                    	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
                                                                                                    	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
                                                                                                    	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
                                                                                                    	at online.devliving.mobilevisionpipeline.camera.CameraSource$FrameProcessingRunnable.release(CameraSource.java:1140)
                                                                                                    	at online.devliving.mobilevisionpipeline.camera.CameraSource.release(CameraSource.java:331)
                                                                                                    	at online.devliving.mobilevisionpipeline.camera.CameraSourcePreview.release(CameraSourcePreview.java:92)
                                                                                                    	at info.hannes.cvscanner.DocumentScannerFragment.onDestroy(DocumentScannerFragment.java:267)
                                                                                                    	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3360)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:781)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:335)
                                                                                                    	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
                                                                                                    	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:615)
                                                                                                    	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:350)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2971)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2922)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:259)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
                                                                                                    	at android.app.Activity.performDestroy(Activity.java:8864)
                                                                                                    	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
                                                                                                    	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
                                                                                                    	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113) 
                                                                                                    	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) `

**Comment by hannesa2** [comment]
You could give recent master a new try
